# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.26
# 

Name:       qca-ossl

# >> macros
# << macros

Summary:    OpenSSL plugin for the Qt Cryptographic Architecture v2
Version:    2.0.0
Release:    beta3
Group:      System/Libraries
License:    LGPLv2
URL:        http://delta.affinix.com/qca/
Source0:    %{name}-%{version}.tar.bz2
Source100:  qca-ossl.yaml
BuildRequires:  pkgconfig(QtCore) < 5
BuildRequires:  pkgconfig(qca2)
BuildRequires:  pkgconfig(openssl)

%description
This plugin provides support for TLS, CMS, X.509, RSA, DSA, Diffie-Hellman, PKCS#7, PKCS#12, SHA0, SHA1, SHA224, SHA256, SHA384, SHA512, MD2, MD4, MD5, RIPEMD160, Blowfish, DES, 3DES, AES128, AES192, AES256, CAST5, HMAC(SHA1, MD5, RIPEMD160), PBKDF1(MD2, SHA1), PBKDF2(SHA1).

%prep
%setup -q -n %{name}-%{version}/%{name}

# >> setup
# << setup

%build
# >> build pre
./configure
# << build pre


make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post

%files
%defattr(-,root,root,-)
/usr/lib/qt4/plugins/crypto/libqca-ossl.so
# >> files
# << files
